forum/urls.py
from django.conf.urls import patterns, include, url
import settings

urlpatterns = patterns('forum.views',
    url(r'^board/$','forum_board_page'),
    url(r'^board/(?P<bid>\d+)/$','forum_thread_page'),
    url(r'^board/goto/$','set_thread_per_page'),
    url(r'^board/thread/goto/$','set_post_per_page'),
    url(r'^board/(?P<bid>\d+)-(?P<page>\d+)/$','forum_thread_page'),    
    url(r'^board/(?P<bid>\d+)-(?P<page>\d+)-(?P<thread_per_page>\d+)/$','forum_thread_page'),
    url(r'^board/thread/(?P<tid>\d+)/$','forum_post_page'),
    url(r'^board/thread/(?P<tid>\d+)-(?P<page>\d+)/$','forum_post_page'),
    url(r'^board/thread/(?P<tid>\d+)-(?P<page>\d+)-(?P<post_per_page>\d+)/$','forum_post_page'),
    #url(r'^board/(?P<bid>)\d+/$',''),
    url(r'^admin/sync_board/$','sync_all_board'),
    url(r'^profile/image$','forum_uploadimage_page'),
    url(r'^profile/password$','forum_password_page'),
    url(r'^profile/basic$','forum_basicprofile_page'),
    url(r'^profile/$','forum_profile_page'),
)

mysite/urls.py
from django.conf.urls import patterns, include, url
import settings

from django.contrib import admin
admin.autodiscover()

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()  # dajaxice
# dajaxice 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import public
urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^public/',include('public.urls')),
    url(r'^forum/',include('forum.urls')),
    # dajaxice
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'^image_upload/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True }),
)

urlpatterns += staticfiles_urlpatterns()

forum/models.py
# Models for forum

from django.db import models
from public.models import *
from django import forms

################################
# Image Form ###################
################################

class ImageForm(forms.Form):
    img = forms.ImageField()

################################
# Type Definition ##############
################################

class ProfileType(models.Model):
    name = models.CharField(max_length=50)
    page = models.CharField(max_length=128)
    def __unicode__(self):
        return self.name + ' @ ' + self.page

class OperationType(models.Model):
    name = models.CharField(max_length=50)
    def __unicode__(self):
        return self.name

# Configured using the admin page, static when the forum is operating
class BoardType(models.Model):
    name = models.CharField(max_length=50)
    order = models.IntegerField(unique=True)
    def __unicode__(self):
        return self.name + '@' + str(self.order)

class ThreadType(models.Model): # Automatic primary key added
    name = models.CharField(max_length=50)
    # Only this board will allow this type. You can also let it to be NULL
    bid = models.ForeignKey('BoardBasic',null=True) 
    def __unicode__(self):
        return self.name

class MessageType(models.Model):
    name = models.CharField(max_length=50)
    def __unicode__(self):
        return self.name

class FloorType(models.Model):
    name = models.CharField(max_length=10)
    def __unicode__(self):
        return self.name

class ForumSystemAdmin(models.Model):
    uid = models.ForeignKey(UserBasic)
    def __unicode__(self):
        return str(self.uid.uid) + ': ' + self.uid.username
    
class BoardBasic(models.Model):
    bid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=80)
    thread_num = models.IntegerField()
    post_num = models.IntegerField()
    # There is a constraint, i.e. the bid of this type must be the same in
    # ThreadType
    btype = models.ForeignKey(BoardType)
    # We must use the real ID instead of the ForeignKey abstract to do this
    # since there is a circular reference
    last_thread = models.ForeignKey('ThreadBasic',null=True,blank=True)
    # last_thread_time can be just retrieved using the foreign key

    def __unicode__(self):
        return "Board " + self.name

##########################
# About thread ###########
##########################
class ThreadBasic(models.Model):
    tid = models.AutoField(primary_key=True)
    bid = models.ForeignKey(BoardBasic)
    uid = models.ForeignKey(UserBasic,related_name='created_thread')
    title = models.CharField(max_length=120)
    #text = models.TextField()
    ttype = models.ForeignKey(ThreadType)
    last_reply_time = models.DateTimeField() # Create is also reply
    last_reply_user = models.ForeignKey(UserBasic, related_name='last_reply')
    create_time = models.DateTimeField(auto_now_add=True)
    num_of_read = models.IntegerField()
    num_of_reply = models.IntegerField()
    #upvote = models.IntegerField()
    #downvote = models.IntegerField()
    privilege = models.IntegerField() # 0 means normal, -1 means always on top

    locked = models.BooleanField()  # can't reply
    hided = models.BooleanField()   # won't display, can't read
    highlighted = models.BooleanField()
    # Stores a HEX color RGB representation, without the leading '#'
    highlight_color = models.ForeignKey(ColorType,null=True,blank=True)
    # This is used to post some blog on the personal space
    # private = models.BooleanField()
    def __unicode__(self):
        return self.title

"""
class SuperThread(models.Model):
    stid = models.AutoField(primary_key=True)
    bid = models.OneToManyField(BoardBasic)
    uid = models.ForeignKey(ForumSystemAdmin)
    title = models.CharField(max_length=120)
    text = models.TextField()
    sttype = models.ForeignKey(ThreadType)
    create_time = models.DateTimeField(auto_now_add=True)
    """
"""

class ThreadExtend(models.Model):
    tid = models.OneToOneField(ThreadBasic)
    upvote = models.IntegerField()
    downvote = models.IntegerField()
"""
    
##########################
# About Post #############
##########################
class PostBasic(models.Model):
    pid = models.AutoField(primary_key=True)
    tid = models.ForeignKey(ThreadBasic)
    uid = models.ForeignKey(UserBasic)
    text = models.TextField()
    upvote = models.IntegerField()
    downvote = models.IntegerField()
    post_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now_add=True)
    floor = models.IntegerField()
    privilege = models.IntegerField()
    def __unicode__(self):
        if len(self.text) > 30:
            return self.text[:30] + ' @ ' + str(self.tid.tid)
        else:
            return self.text + ' @ ' + str(self.tid.tid)
##########################
# About Reply ############
##########################
class ReplyBasic(models.Model):
    rid = models.AutoField(primary_key=True)
    pid = models.ForeignKey(PostBasic)
    uid = models.ForeignKey(UserBasic)
    text = models.TextField()
    post_date = models.DateTimeField(auto_now_add=True)
    def __unicode__(self):
        if len(self.text) > 30:
            return self.text[:30] + ' @ ' + str(self.pid.pid)
        else:
            return self.text + ' @ ' + str(self.pid.pid)
    
##########################
# About User Relation ####
##########################

class UserFriend(models.Model):
    uid_1 = models.ForeignKey(UserBasic,related_name='friend_1')
    uid_2 = models.ForeignKey(UserBasic,related_name='friend_2')
    friend_date = models.DateTimeField(auto_now_add=True)
    
class UserMessage(models.Model):
    from_uid = models.ForeignKey(UserBasic,related_name='msg_from')
    to_uid = models.ForeignKey(UserBasic,related_name='msg_to')
    mtype = models.IntegerField() # No configurable types because this is static
    highlight = models.BooleanField()
    msg_date = models.DateTimeField(auto_now_add=True)

class UserVote(models.Model):
    uid = models.ForeignKey(UserBasic)
    pid = models.ForeignKey(PostBasic)
    vote_time = models.DateTimeField(auto_now_add=True)

forum/templates/forum_basic_profile.html
{% load string_convert %}

<style type="text/css">
	#signature, #title { width: 150% }
</style>

<h2>Basic Personal Profile</h2>
<table>
	<tr id='username_row'>
		<td><strong>User Name </strong></td>
		<td>{{ meta.user_basic.username }}</td>
	</tr>
	<tr>
		<td><strong>UID </strong></td>
		<td>{{ meta.user_basic.uid }}<td>
	</tr>
	<tr>
		<td><strong>User Image </strong></td>
		<td><img src='/{{meta.user_basic.userextend.image}}' height=120 width=120 /></td>
	</tr>
	<tr>
		<td><strong>Password </strong></td>
		<td>**********<td>
	</tr>
	<tr>
		<td><strong>Threads </strong></td>
		<td>{{ meta.user_basic.userextend.num_of_threads }}</td>
	</tr>
	<tr>
		<td><strong>Posts </strong></td>
		<td>{{ meta.user_basic.userextend.num_of_posts }}</td>
	</tr>
	<tr>
		<td><strong>Money </strong></td>
		<td>{{ meta.user_basic.userextend.money }}</td>
	</tr>
	<tr>
		<td><strong>Credit </strong></td>
		<td>{{ meta.user_basic.userextend.credit }}</td>
	</tr>
	<tr>
		<td><strong>Date of Registration </strong></td>
		<td>{{ meta.user_basic.userextend.register_date|num_date }}</td>
	</tr>
	<tr>
		<td><strong>Title </strong></td>
		<td>
			<input id='title' value='{{ meta.user_basic.userextend.title }}' onchange='refresh_title_tip(this)' onkeypress='refresh_title_tip(this)'>
			<button onclick='update_title()'>Update</button>
			<span id='title_tip'></span>
		</td>
	</tr>
	<tr>
		<td><strong>Signature </strong></td>
		<td>
			<input id='signature' value='{{ meta.user_basic.userextend.signature }}' onchange='refresh_signature_tip(this)' onkeypress='refresh_signature_tip(this)'>
			<button onclick='update_signature()'>Update</button>
			<span id='signature_tip'></span>
		</td>
	</tr>

</table>

forum/templates/forum_board.html
{% extends 'general_base.html' %}
{% load string_convert %}

{% block title %}
All Boards
{% endblock title %}

{% block head %}
<!--
<style type='text/css'>
.board_type { background-color: #BBCCDD; padding: 5px }
.board_title_description {width: 60%}
.board_thread_post_num {width: 20%; text-align: center}
.board_last_reply { width: 20% }
#main_frame { margin: 0% 5% 50px 5%; width: 90%; }
.board_list { background-color: #DDCCBB; padding: 5px }
table {width: 100%}
</style>
//-->

<style tyep='text/css'>
.type-name {
	margin-left: 5px;
}
</style>
{% endblock head %}

{% block body %}
<div class="container" id='main_frame'>
	<h1>View All Boards</h1>
	
	{% for board_type in boards %}
	<div class="panel panel-primary">
	    <div class="panel-heading">
		<h3 class="panel-title"><span class="glyphicon glyphicon-certificate"></span><span class="type-name">{{ board_type.name }}</span></h3>
	    </div>
	    <div class="panel-body">
		{% for i in board_type.board %}		
		    <div class='col-md-8'>
		        <a class='board_title' href='{% url forum.views.forum_thread_page bid=i.bid %}'>{{ i.name }}</a>
			<div class='board_description'>{{ i.description }}</div>
		    </div>
		    <div class='col-md-1'>
			{{ i.thread_num }}<br />{{ i.post_num }}
		    </div>
		    <div class='col-md-3'>
			{% if i.last_thread %}
			<span>{{ i.last_thread.last_reply_time|readable_delta:meta.now }}</span><br />
			<span>{{ i.last_thread.title }}</span>
			{% else %}
			<span>No Thread</span>
			{% endif %}
		    </div>
		{% endfor %}
	    </div>
	</div>
	<br />
	{% endfor %}
</div>
{% endblock body %}

forum/templates/forum_edit_block.html
				<td class='right_column'>
					<div id='new_post_text_style_wrapper'>
						<span class='new_post_text_style'><a href='javascript:;' onclick='make_bold()'>B</a></span>
						<span class='new_post_text_style' data-toggle="modal" data-target="#color_selector">
							<a href='javascript:;'>COLOR</a>
						</span>
						<span class='new_post_text_style' data-toggle="modal" data-target="#image_selector">
							<a href='javascript:;'>IMG</a>
						</span>
						<span class='new_post_text_style' data-toggle='modal' data-target='#size_selector'>
							<a href='javascript:;'>SIZE</a>
						</span>
						<span class='new_post_text_style' id='after_render_checkbox'>
							<input type='checkbox' id='after_render' onclick='get_rendered_text(this)'>&nbsp;<label for='after_render'>After Render</label>
						</span>
					</div>
					<div id='new_post_text_wrapper'>
						<div contenteditable='true' id='after_render_display'></div>
						<textarea id='new_post_text'></textarea>
					</div>
					<button id='make_new_post_button' onclick='make_new_post()' class='btn'>Submit</button>

					<!-- Modal -->
<div class="modal fade" id="color_selector" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Choose A Color</h4>
      </div>
      <div class="modal-body">
			<div>Please Choose A Color:</div>
			<input type="text" value="000" id="post_text_color" class="pick-a-color">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-dismiss='modal' onclick='add_color();'>OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="image_selector" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Choose A Color</h4>
      </div>
      <div class="modal-body">
			<div><pre>URL:    <input type="text" value="" id="post_image_url"></pre></div>
			<div><pre>Width:  <input type='text' value='' id='post_image_width'></pre></div>
			<div><pre>Height: <input type='text' value='' id='post_image_height'></pre></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-dismiss='modal' onclick='add_image();'>OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="size_selector" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Choose A Size</h4>
      </div>
      <div class="modal-body">
			<div>Please Enter The Size:</div>
			<div><pre>Size: <input type="text" value="" id="post_text_size"></pre></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-dismiss='modal' onclick='add_size();'>OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

forum/templates/forum_post_block.html
			{% load string_convert %}

			<tr class='single_post'>
				<td class='post_info left_column' {% if i.uid.userextend.signature %}rowspan=2{% endif %}>
					<div class='post_wrap'>
						<div class='poster_name first_line'><strong>{{ i.uid.username }}</strong></div>
						<div class='poster_image'><img height=120 width=120 src='/{{ i.uid.userextend.image }}' /></div>
						<br />
						<!--
						<div class='poster_statistic'><pre>{{i.uid.userextend.num_of_threads}}   |   {{i.uid.userextend.num_of_posts}}   |   {{i.uid.userextend.privilege}}</pre></div>
						<div><pre> Threads   Posts   Level</pre></div>
						-->
						{% if i.uid.userextend.title %}
						<span class='user_title'>{{ i.uid.userextend.title }}</span>
						<br /><br />
						{% endif %}
						
						<div class='poster_extend'>
							<table id='poster_extend_table'>
								<tr id='poster_level'>
									<td id='poster_level_tag' class='poster_extend_tag'>Level</td>
									<td id='poster_level' class='poster_extend_value'>{{i.uid.userextend.privilege}}<td>
								</tr>
								<tr id='poster_level'>
									<td id='poster_uid_tag' class='poster_extend_tag'>UID</td>
									<td id='poster_uid' class='poster_extend_value'>{{i.uid.uid}}<td>
								</tr>
								<tr id='poster_level'>
									<td id='poster_money_tag' class='poster_extend_tag'>Money</td>
									<td id='poster_money' class='poster_extend_value'>{{i.uid.userextend.money}}<td>
								</tr>
								<tr id='poster_level'>
									<td id='poster_credit_tag' class='poster_extend_tag'>Credit</td>
									<td id='poster_credit' class='poster_extend_value'>{{i.uid.userextend.credit}}<td>
								</tr>
								<tr id='poster_level'>
									<td id='poster_register_time_tag' class='poster_extend_tag'>Register</td>
									<td id='poster_register_time' class='poster_extend_value'>{{i.uid.userextend.register_date|num_date}}<td>
								</tr>

							</table>
						</div>
					</div>
				</td>
				<td class='post_body right_column'>
					<div class='post_wrap'>
						<div class='first_line post_datetime'>
							<span>Posted: {{ i.post_date|readable_delta:meta.now }}</span>
							<span class='post_floor'>{{ i.floor|floor_to_text:floor_name_num }}</span>
						</div>
						{% if i.post_date != i.modify_date %}
						<div class='post_modify_tip'>
							<span>This post has been edited {{ i.modify_date|readable_delta:meta.now }}</span>
						</div>
						{% endif %}
						{% autoescape off %}
						<div class='post_content' id='floor_{{ i.floor }}'>
							<pre id='post_text_{{ i.pid }}'>{{ i.text|post_text_render:i.tid.tid }}</pre>
						</div>
						{% endautoescape %}
						<div class='post_reply' id='post_reply_{{ i.pid }}'> {# Used with ajax #}
							<script type="text/javascript">
								Dajaxice.forum.get_post_details(load_details,{"post_id": {{i.pid}}, "request_page": 1})
							</script>
						</div>
					</div>
				</td>
			</tr>
			{% if i.uid.userextend.signature %}
			<tr class='user_signature_row'>
				<td class='user_signature_col right_column'>
					<span class='signature'>{{ i.uid.userextend.signature }}</span>
				</td>
			</tr>
			{% endif %}
			{% if meta.user_basic %}
			<tr class='single_post_bottom_line'>
				<td class='left_column'>&nbsp;</td>
				<td class='right_column right_bottom_line'>
					<div class='bottom_post_bar'>
						<span class='send_reply bottom_post_bar_element'><a href='javascript:;' data-toggle='modal' data-target='#reply_dialog' onclick='window.recent_pid={{i.pid}}'>Comment</a></span>
						<span class='send_post bottom_post_bar_element'><a href='#new_post_text' onclick='window.recent_pid={{i.pid}}; window.recent_floor={{ i.floor }}; set_quote_text()'>Reply</a></span>
						<span class='upvote bottom_post_bar_element'><a id="votes_up_{{ i.pid }}"  href='javascript:;' onclick='send_vote({{ i.pid }},1)'>Upvote</a></span>
						<span class='downvote bottom_post_bar_element'><a id="votes_down_{{ i.pid }}" href='javascript:;' onclick='send_vote({{ i.pid }},-1)'>Downvote</a></span>
					</div>
				</td>
			</tr>
			{% endif %}

forum/templates/forum_profile_page.html
{% extends 'general_base.html' %}

{% block title %}
Personal Profile
{% endblock title %}

{% block head %}

{% load string_convert %}
{% load dajaxice_templatetags %}
{% dajaxice_js_import %}

<style type="text/css">
	#main_frame { width: 90%; margin: 0 5% 0 5%; }
	#profile_table { width: 100%; border: none; border: 1px solid black  }
	#content { margin: 0 5% 20px 5% }
	.left_column { background-color: #ffffcc; vertical-align: top; width: 10%; -align: }
	.right_column { background-color: #ffccff; width: 90% }
	.profile_catalog_div { text-align: center;  width: 101%; padding: 10px 0px 10px 0; }
	.category_list_item { display: block ;width: 100%;float: left  }
	.category_list { list-style: none }
</style>

<script type="text/javascript">
<!--
	function refresh_title_tip(ta)
	{
		tt = document.getElementById('title_tip');
		val_len = ta.value.length
		if(val_len > 20) tt.innerHTML = 'Too Long';
		else tt.innerHTML = (20 - val_len) + ' Character(s) Left';
		return
	}

	function refresh_signature_tip(ta)
	{
		tt = document.getElementById('signature_tip');
		val_len = ta.value.length
		if(val_len > 50) tt.innerHTML = 'Too Long';
		else tt.innerHTML = (50 - val_len) + ' Character(s) Left';
		return
	}

	function refresh_signature(data)
	{
		if(data.success == true) 
		{
			document.getElementById('signature').value = data.content;
			document.getElementById('signature_tip').innerHTML = 'Success'
		}
		else document.getElementById('signature_tip').innerHTML = data.reason
	}

	function refresh_title(data)
	{
		if(data.success == true) 
		{
			document.getElementById('title').value = data.content;
			document.getElementById('title_tip').innerHTML = 'Success'
		}
		else document.getElementById('title_tip').innerHTML = data.reason
	}

	function update_title()
	{
		ta = document.getElementById('title')
		Dajaxice.forum.update_title(refresh_title,{'new_title': ta.value})
		return
	}

	function update_signature()
	{
		ta = document.getElementById('signature')
		Dajaxice.forum.update_signature(refresh_signature,{'new_signature': ta.value})
		return
	}

//-->
</script>


<script type="text/javascript">
<!--
	function change_category_color(cn)
	{
		$('.profile_catalog_div').css('backgroundColor','#ffffcc');
		var ce = document.getElementById(cn)
		ce.style.backgroundColor = '#ffccff'
		return;
	}

	function refresh_content(data)
	{
		if(data.success == false)
		{
			alert('Internal Error. Please Contact the administrator');
			return;
		}
		document.getElementById('content').innerHTML = data.content;
		return;
	}
//-->
</script>

{% endblock head %}

{% block body %}
<div id='main_frame'>
	<h1>User Profile</h1>
	<table id='profile_table'>
		<tr>
			<td id='catalog' class='left_column'>
				<!-- <ul class='category_list'> -->
					{% for i in profile_type %}
					<!--<li class='category_list_item'> -->
						<div class='profile_catalog_div' id='category_{{ i.id }}'>
							<a href='javascript:;' onclick='Dajaxice.forum.get_page(refresh_content,{"page_view": "{{i.page}}" }); change_category_color("category_{{ i.id }}")'>{{ i.name }}</a>
						</div>
					<!--</li>-->
					{% endfor %}
				<!--</ul>-->
			</td>
			<td id='catalog_content' class='right_column'>
				<div id='content'>
					<h2>This is the page to configue user profile</h2>
					<p>Please choose from the left column.</p>
				</div>
			</td>
		</tr>
	</table>
</div>
{% endblock body %}

forum/templates/forum_thread.html
{% extends 'general_base.html' %}
{% block title %}
{{ board_basic.name }}
{% endblock title %}

{% block head %}
<!--
<style type='text/css'>
#main_frame { margin: 0% 5% 50px 5%; width: 90%; position: relative }
.thread_type { width: 10%; font-size: 70% }
.thread_title { width: 60% }
.thread_create_time { width: 10%; font-size: 70% }
.thread_reply_read { width: 5%; font-size: 70% }
.thread_last_reply { width: 10%; font-size: 70% }
#page_selector { padding: 5px 0 5px 0; position: absolute; right: 0}
.page_navigation { color: blue; margin: 5px 5px 5px 5px }
#other_uppermost_sep { background-color: #BBCCDD }
#uppermost_table { width: 100%; text-align: left }
#your_position {font-size: 70%;}
#set_thread_per_page_form { display: inline; margin: 5px }
#set_thread_per_page { position: absolute; right: 0 }
</style>
//-->

<link href="/static/css/forumthread.css" rel="stylesheet">

{% endblock head %}

{% block body %}
{% load string_convert %}

<div class="container" id='main_frame'>
	<h1>{{ board_basic.name }}</h1>
	<div class="your_position" id='your_position'>
	    <div class="col-md-8">
		<ol class="breadcrumb">
			<li><a href='{%url forum.views.forum_board_page%}'>Forum</a></li>
			<li><a href='{% url forum.views.forum_thread_page bid=board_basic.bid %}'>{{ board_basic.name }}</a></li>
			<li><a href='{% url forum.views.forum_thread_page bid=board_basic.bid page=current_page thread_per_page=thread_per_page %}'>Page {{current_page}}</a></li>
		</ol>
	    </div>
	    <div class="col-md-4">
		<span id='set_thread_per_page'>
		<form id='set_thread_per_page_form' action='{% url forum.views.set_thread_per_page %}' method='POST'>
			{% csrf_token %}
			<input name='bid' type='hidden' value='{{ board_basic.bid }}'></input>
			Page <input name='goto_page' size='4'></input>
			Thread / Page <input name='object_per_page' size='4'></input>
			<input type='submit' value='Go'></input>
		</form>
		</span>
	    </div>
	</div>
	<br />
	{% if threads.uppermost %}
	<div class="panel panel-danger" id='uppermost'>
		<ul class="list-group">
			{% for i in threads.uppermost %}
			{% include 'forum_thread_block.html' %}
			{% endfor %}
		</ul>
	</div>
	{% endif %}
	<div id='other_uppermost_sep'>&nbsp;</div>
	{% if threads.other %}
	<div class="panel panel-primary" id='other'>
		<ul class="list-group">

			{% for i in threads.other %}
			{% include 'forum_thread_block.html' %}
			{% endfor %}

		</ul>
	</div>
	{% endif %}
	<ul class="pagination" id='page_selector'>

		{% if current_page != 1 %}
			<li><a href='{% url forum.views.forum_thread_page board_basic.bid 1 thread_per_page %}'>&laquo;</a></li>
			<li><a href='{% url forum.views.forum_thread_page board_basic.bid current_page|add:-1 thread_per_page %}'>&lt;</a></li>
		{% endif %}
		{% for i in total_page|get_range:current_page %} {# starts at 1 #}
			{% if i != current_page %}
				<li><a href='{% url forum.views.forum_thread_page board_basic.bid i thread_per_page %}'>{{i}}</a></li>
			{% else %}
				<li class="active"><a href="#">{{i}}</a></li>
			{% endif %}
		{% endfor %}
		{% if current_page != total_page %}
			<li><a href='{% url forum.views.forum_thread_page board_basic.bid current_page|add:1 thread_per_page %}'>&gt;</a></li>
			<li><a href='{% url forum.views.forum_thread_page board_basic.bid total_page thread_per_page %}'>&raquo;</a></li>
		{% endif %}

	</ul>
</div>
{% endblock body %}

forum/templates/forum_upload_image.html
<h2>Upload Your Image</h2>
<p>Choose an image file from your local file system, and uplaod that to the server as your own user image. This image will be presented when you make a new post or comment.</p>

<form action='{% url forum.views.forum_uploadimage_page %}' method='post' enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.img.errors }}
	<label for='id_img'>Local File Path: </label>
	{{ form.img }}
	<br />
	<input type='submit' value='Submit'>
</form>